include ../../make/stdprefix.mk

NESTING := ../../
OUT_DIR := ../../lib

LIB = mist_controllers
SOURCE_NAMES = Controller.cpp ControllerConfig.cpp ControllersStd.cpp DelugeController.cpp MistController.cpp NullController.cpp

all : dirs $(OBJECTS) $(LIB)
	
include ../../make/stdsuffix.mk
