include ../../make/stdprefix.mk

NESTING := ../../
OUT_DIR := ../../lib

LIB = mist_controllers
SOURCE_NAMES = Controller.cpp NullController.cpp ControllerConfig.cpp DelugeController.cpp MistController.cpp MistSchedule.cpp ControllersStd.cpp

all : dirs $(OBJECTS) $(LIB)
	
include ../../make/stdsuffix.mk
